//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Cypher.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CypherParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface ICypherVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.cypher"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCypher([NotNull] CypherParser.CypherContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.queryOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQueryOptions([NotNull] CypherParser.QueryOptionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.anyCypherOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnyCypherOption([NotNull] CypherParser.AnyCypherOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.cypherOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCypherOption([NotNull] CypherParser.CypherOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.versionNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVersionNumber([NotNull] CypherParser.VersionNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.explain"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplain([NotNull] CypherParser.ExplainContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.profile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProfile([NotNull] CypherParser.ProfileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.configurationOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConfigurationOption([NotNull] CypherParser.ConfigurationOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] CypherParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuery([NotNull] CypherParser.QueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.regularQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRegularQuery([NotNull] CypherParser.RegularQueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.bulkImportQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBulkImportQuery([NotNull] CypherParser.BulkImportQueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.periodicCommitHint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPeriodicCommitHint([NotNull] CypherParser.PeriodicCommitHintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.loadCSVQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoadCSVQuery([NotNull] CypherParser.LoadCSVQueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.union"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnion([NotNull] CypherParser.UnionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.singleQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleQuery([NotNull] CypherParser.SingleQueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.singlePartQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSinglePartQuery([NotNull] CypherParser.SinglePartQueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.readOnlyEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReadOnlyEnd([NotNull] CypherParser.ReadOnlyEndContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.readUpdateEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReadUpdateEnd([NotNull] CypherParser.ReadUpdateEndContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.updatingEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUpdatingEnd([NotNull] CypherParser.UpdatingEndContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.multiPartQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiPartQuery([NotNull] CypherParser.MultiPartQueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.readPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReadPart([NotNull] CypherParser.ReadPartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.updatingPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUpdatingPart([NotNull] CypherParser.UpdatingPartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.updatingStartClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUpdatingStartClause([NotNull] CypherParser.UpdatingStartClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.updatingClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUpdatingClause([NotNull] CypherParser.UpdatingClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.readingClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReadingClause([NotNull] CypherParser.ReadingClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand([NotNull] CypherParser.CommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.createUniqueConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreateUniqueConstraint([NotNull] CypherParser.CreateUniqueConstraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.createNodePropertyExistenceConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreateNodePropertyExistenceConstraint([NotNull] CypherParser.CreateNodePropertyExistenceConstraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.createRelationshipPropertyExistenceConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreateRelationshipPropertyExistenceConstraint([NotNull] CypherParser.CreateRelationshipPropertyExistenceConstraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.createIndex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreateIndex([NotNull] CypherParser.CreateIndexContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.dropUniqueConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDropUniqueConstraint([NotNull] CypherParser.DropUniqueConstraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.dropNodePropertyExistenceConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDropNodePropertyExistenceConstraint([NotNull] CypherParser.DropNodePropertyExistenceConstraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.dropRelationshipPropertyExistenceConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDropRelationshipPropertyExistenceConstraint([NotNull] CypherParser.DropRelationshipPropertyExistenceConstraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.dropIndex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDropIndex([NotNull] CypherParser.DropIndexContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex([NotNull] CypherParser.IndexContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.uniqueConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUniqueConstraint([NotNull] CypherParser.UniqueConstraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.nodePropertyExistenceConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNodePropertyExistenceConstraint([NotNull] CypherParser.NodePropertyExistenceConstraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.relationshipPropertyExistenceConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationshipPropertyExistenceConstraint([NotNull] CypherParser.RelationshipPropertyExistenceConstraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.relationshipPatternSyntax"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationshipPatternSyntax([NotNull] CypherParser.RelationshipPatternSyntaxContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.loadCSV"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoadCSV([NotNull] CypherParser.LoadCSVContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.match"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatch([NotNull] CypherParser.MatchContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.unwind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnwind([NotNull] CypherParser.UnwindContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.merge"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMerge([NotNull] CypherParser.MergeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.mergeAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMergeAction([NotNull] CypherParser.MergeActionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.create"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate([NotNull] CypherParser.CreateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.createUnique"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreateUnique([NotNull] CypherParser.CreateUniqueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSet([NotNull] CypherParser.SetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.setItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetItem([NotNull] CypherParser.SetItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.delete"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDelete([NotNull] CypherParser.DeleteContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.remove"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRemove([NotNull] CypherParser.RemoveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.removeItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRemoveItem([NotNull] CypherParser.RemoveItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.foreach"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForeach([NotNull] CypherParser.ForeachContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.inQueryCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInQueryCall([NotNull] CypherParser.InQueryCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.standaloneCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStandaloneCall([NotNull] CypherParser.StandaloneCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.yieldItems"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitYieldItems([NotNull] CypherParser.YieldItemsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.yieldItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitYieldItem([NotNull] CypherParser.YieldItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.with"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWith([NotNull] CypherParser.WithContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn([NotNull] CypherParser.ReturnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.returnBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnBody([NotNull] CypherParser.ReturnBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.returnItems"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnItems([NotNull] CypherParser.ReturnItemsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.returnItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnItem([NotNull] CypherParser.ReturnItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.order"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrder([NotNull] CypherParser.OrderContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.skip"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSkip([NotNull] CypherParser.SkipContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.limit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLimit([NotNull] CypherParser.LimitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.sortItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSortItem([NotNull] CypherParser.SortItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.hint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHint([NotNull] CypherParser.HintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStart([NotNull] CypherParser.StartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.startPoint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStartPoint([NotNull] CypherParser.StartPointContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.lookup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLookup([NotNull] CypherParser.LookupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.nodeLookup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNodeLookup([NotNull] CypherParser.NodeLookupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.relationshipLookup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationshipLookup([NotNull] CypherParser.RelationshipLookupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.identifiedIndexLookup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifiedIndexLookup([NotNull] CypherParser.IdentifiedIndexLookupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.indexQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexQuery([NotNull] CypherParser.IndexQueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.idLookup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdLookup([NotNull] CypherParser.IdLookupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.literalIds"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralIds([NotNull] CypherParser.LiteralIdsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.where"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhere([NotNull] CypherParser.WhereContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPattern([NotNull] CypherParser.PatternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.patternPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPatternPart([NotNull] CypherParser.PatternPartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.anonymousPatternPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnonymousPatternPart([NotNull] CypherParser.AnonymousPatternPartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.shortestPathPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShortestPathPattern([NotNull] CypherParser.ShortestPathPatternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.patternElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPatternElement([NotNull] CypherParser.PatternElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.nodePattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNodePattern([NotNull] CypherParser.NodePatternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.patternElementChain"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPatternElementChain([NotNull] CypherParser.PatternElementChainContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.relationshipPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationshipPattern([NotNull] CypherParser.RelationshipPatternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.relationshipDetail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationshipDetail([NotNull] CypherParser.RelationshipDetailContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.properties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProperties([NotNull] CypherParser.PropertiesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.relType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelType([NotNull] CypherParser.RelTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.relationshipTypes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationshipTypes([NotNull] CypherParser.RelationshipTypesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.nodeLabels"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNodeLabels([NotNull] CypherParser.NodeLabelsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.nodeLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNodeLabel([NotNull] CypherParser.NodeLabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.rangeLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRangeLiteral([NotNull] CypherParser.RangeLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.labelName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabelName([NotNull] CypherParser.LabelNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.relTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelTypeName([NotNull] CypherParser.RelTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] CypherParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.orExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrExpression([NotNull] CypherParser.OrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.xorExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXorExpression([NotNull] CypherParser.XorExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpression([NotNull] CypherParser.AndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.notExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotExpression([NotNull] CypherParser.NotExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.comparisonExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparisonExpression([NotNull] CypherParser.ComparisonExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.addOrSubtractExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddOrSubtractExpression([NotNull] CypherParser.AddOrSubtractExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.multiplyDivideModuloExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplyDivideModuloExpression([NotNull] CypherParser.MultiplyDivideModuloExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.powerOfExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPowerOfExpression([NotNull] CypherParser.PowerOfExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.unaryAddOrSubtractExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryAddOrSubtractExpression([NotNull] CypherParser.UnaryAddOrSubtractExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.stringListNullOperatorExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringListNullOperatorExpression([NotNull] CypherParser.StringListNullOperatorExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.regularExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRegularExpression([NotNull] CypherParser.RegularExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.propertyOrLabelsExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyOrLabelsExpression([NotNull] CypherParser.PropertyOrLabelsExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtom([NotNull] CypherParser.AtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] CypherParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.booleanLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanLiteral([NotNull] CypherParser.BooleanLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.listLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListLiteral([NotNull] CypherParser.ListLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.reduce"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReduce([NotNull] CypherParser.ReduceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.partialComparisonExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPartialComparisonExpression([NotNull] CypherParser.PartialComparisonExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.parenthesizedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthesizedExpression([NotNull] CypherParser.ParenthesizedExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.relationshipsPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationshipsPattern([NotNull] CypherParser.RelationshipsPatternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.filterExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFilterExpression([NotNull] CypherParser.FilterExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.idInColl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdInColl([NotNull] CypherParser.IdInCollContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.functionInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionInvocation([NotNull] CypherParser.FunctionInvocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.functionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionName([NotNull] CypherParser.FunctionNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.explicitProcedureInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicitProcedureInvocation([NotNull] CypherParser.ExplicitProcedureInvocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.implicitProcedureInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImplicitProcedureInvocation([NotNull] CypherParser.ImplicitProcedureInvocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.procedureResultField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedureResultField([NotNull] CypherParser.ProcedureResultFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.procedureName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedureName([NotNull] CypherParser.ProcedureNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.namespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace([NotNull] CypherParser.NamespaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.listComprehension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListComprehension([NotNull] CypherParser.ListComprehensionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.patternComprehension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPatternComprehension([NotNull] CypherParser.PatternComprehensionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.propertyLookup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyLookup([NotNull] CypherParser.PropertyLookupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.caseExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseExpression([NotNull] CypherParser.CaseExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.caseAlternatives"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseAlternatives([NotNull] CypherParser.CaseAlternativesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable([NotNull] CypherParser.VariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.numberLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberLiteral([NotNull] CypherParser.NumberLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.mapLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMapLiteral([NotNull] CypherParser.MapLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.legacyParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLegacyParameter([NotNull] CypherParser.LegacyParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] CypherParser.ParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.propertyExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyExpression([NotNull] CypherParser.PropertyExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.propertyKeyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyKeyName([NotNull] CypherParser.PropertyKeyNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.integerLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegerLiteral([NotNull] CypherParser.IntegerLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.doubleLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoubleLiteral([NotNull] CypherParser.DoubleLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.schemaName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSchemaName([NotNull] CypherParser.SchemaNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.reservedWord"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReservedWord([NotNull] CypherParser.ReservedWordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.symbolicName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSymbolicName([NotNull] CypherParser.SymbolicNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.leftArrowHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeftArrowHead([NotNull] CypherParser.LeftArrowHeadContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.rightArrowHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRightArrowHead([NotNull] CypherParser.RightArrowHeadContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CypherParser.dash"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDash([NotNull] CypherParser.DashContext context);
}
